# Generated by Django 6.1 on 2026-08-26 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliosnapshot_watchlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['user', 'is_active', 'is_triggered'], name='portfolio_p_user_id_793c70_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', '-date'], name='portfolio_t_portfol_851a43_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['symbol'], name='portfolio_t_symbol_735258_idx'),
        ),
    ]