# Generated by Django 6.0.3 on 2026-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(default='stock', max_length=10)),
                ('current_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('open_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
                ('market_cap', models.BigIntegerField(default=0)),
                ('week_52_high', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('week_52_low', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
